# Generated by Django 4.1.4 on 2022-12-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ing',
            new_name='lng',
        ),
    ]
