# Generated by Django 4.1.4 on 2022-12-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_options_alter_ad_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявлении'},
        ),
    ]
