# Generated by Django 4.1.4 on 2022-12-17 11:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_categories_categorie'),
        ('user', '0001_initial'),
        ('ads', '0004_alter_ad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='categories.categorie'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
