# Generated by Django 4.1.4 on 2022-12-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_categorie_ad_image_alter_ad_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='categorie',
            new_name='category_id',
        ),
    ]
