# Generated by Django 4.1.4 on 2022-12-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_author_ad_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
    ]
