# Generated by Django 4.1.4 on 2022-12-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_rename_author_id_ad_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='address',
        ),
    ]
