# Generated by Django 4.1.4 on 2022-12-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'пользователь'), ('admin', 'администратор'), ('moderator', 'модератор')], default='member', max_length=100),
        ),
    ]
