# Generated by Django 4.1.4 on 2022-12-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_ing_location_lng'),
        ('user', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(to='location.location'),
        ),
    ]
